import React from "react";
import distant from '../assets/images/Distant.png';
import eduprime from '../assets/images/Eduprime.png';
import redstoneForm from '../assets/images/RedstoneFormation.png';
import stellarFlow from '../assets/images/StellarFloz.webp';
import '../assets/styles/Project.scss';

function Project() {
    return(
        <div className="projects-container" id="projects">
            <h1>Personal Projects</h1>
            <div className="projects-grid">
                <div className="project">
                    <a href="https://github.com/lukyyy9/Distant-Bot" target="_blank" rel="noreferrer">
                        <img src={distant} className="zoom" alt="thumbnail" width="100%"/>
                    </a>
                    <a href="https://github.com/lukyyy9/Distant-Bot" target="_blank" rel="noreferrer">
                        <h2>Distant-Bot</h2>
                    </a>
                    <p>The Distant Bot is designed to enrich user interactions within Discord servers by facilitating media sharing from popular social platforms directly into Discord channels.

                    By supporting Instagram Reels, TikTok videos, and Twitter posts, Distant enhances the user experience and community engagement while helping combat social media addiction. This innovative approach allows users to stay within Discord, reducing the urge to switch between apps.

                    A key feature is the ability for users to like shared videos, promoting an interactive and engaging community experience. Users can also share tracks from a music streaming service, and Distant will search and send the links of all platforms for the track.</p>
                </div>
                <div className="project">
                    <a href="https://eduprime.fr/" target="_blank" rel="noreferrer">
                        <img src={eduprime} className="zoom" alt="thumbnail" width="100%"/>
                    </a>
                    <a href="https://eduprime.fr/" target="_blank" rel="noreferrer">
                        <h2>Eduprime</h2>
                    </a>
                    <p>Eduprime is an AI-powered platform designed to revolutionize online learning. With Eduprime, users can create customized courses and exercises automatically generated by artificial intelligence. The platform adapts to individual learning styles, providing interactive and engaging content that helps users master new skills efficiently. Whether for students, professionals, or self-learners, Eduprime makes high-quality education more accessible than ever.</p>
                </div>
                <div className="project">
                    <a href="http://redstoneformations.fr:801/" target="_blank" rel="noreferrer">
                        <img src={redstoneForm} className="zoom" alt="thumbnail" width="100%"/>
                    </a>
                    <a href="http://redstoneformations.fr:801/" target="_blank" rel="noreferrer">
                        <h2>Redstone Formations</h2>
                    </a>
                    <p>Redstone Formations is an online learning platform dedicated to teaching programming and development skills. With a structured curriculum, interactive lessons, and real-world projects, users can progress at their own pace while receiving guidance from industry professionals. The platform covers a wide range of technologies, from web development to artificial intelligence, making it a valuable resource for both beginners and experienced developers.</p>
                </div>
                <div className="project">
                    <a href="https://github.com/Lemine-Mahjoub/StellarFlowCalendarBot" target="_blank" rel="noreferrer">
                        <img src={stellarFlow} className="zoom" alt="thumbnail" width="100%"/>
                    </a>
                    <a href="https://github.com/Lemine-Mahjoub/StellarFlowCalendarBot" target="_blank" rel="noreferrer">
                        <h2>Stellar Flow Calendar</h2>
                    </a>
                    <p>Stellar Flow Calendar is a powerful Discord bot designed to enhance organization and productivity within communities. Featuring an intuitive set of commands, users can schedule events, set reminders, and manage tasks effortlessly. Whether for personal use or large servers, Stellar Flow ensures seamless coordination and helps users stay on top of their commitments.</p>
                </div>
            </div>
        </div>
    )
}

export default Project;
